name: Take-Home
configs:
  Debug: debug
  Release: release

#  schemes
schemes:
  Take-Home:
    build:
      targets:
        Take-Home: all
        Take-HomeTests: [test]
        Take-HomeUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
options:
  bundleIdPrefix: com.thanh.take.home.Take-Home
  deploymentTarget:
    iOS: "13.0"

#  Library
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    version: 5.10.0
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift.git
    version: 6.0.0
  RxCocoa:
    url: https://github.com/ReactiveX/RxSwift.git
    version: 6.0.0
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher.git
    version: 8.3.2
  
#  Targets
targets:
  Take-Home:
    type: application
    platform: iOS
    sources: [Take-Home]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.thanh.take.home.Take-Home
        PRODUCT_BUNDLE_DISPLAY_NAME: Take-Home
        MARKETING_VERSION: 1.2.0         # <- Version
        CURRENT_PROJECT_VERSION: 42
    dependencies:
      - package: Alamofire
      - package: RxSwift
      - package: RxCocoa
      - package: Kingfisher
    scheme:
      testTargets:
        - name: Take-HomeTests
          randomExecutionOrder: true
        - name: Take-HomeUITests
          randomExecutionOrder: true

  Take-HomeTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Take-HomeTests]
    info:
      path: Take-HomeTests/Info.plist
    dependencies:
      - target: Take-Home

  Take-HomeUITests:
    type: bundle.ui-testing
    platform: iOS
    info:
      path: Take-HomeUITests/Info.plist
    sources: [Take-HomeUITests]
    dependencies:
      - target: Take-Home        